arch:
- aarch64
- amd64
- armv7
codenotary: baris@ozdag.net
description: Sync All Your Data Across All Your Devices
hassio_api: true
image: ghcr.io/barisozdag/resiliosync/{arch}
map:
- config:rw
- media:rw
- share:rw
- ssl
name: Resilio Sync
ports:
  55555/tcp: 55555
  8888/tcp: 8888
ports_description:
  55555/tcp: Sync Port
  8888/tcp: Web GUI
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
slug: resiliosync
url: https://github.com/barisozdag/addon-resiliosync
version: 1.0.3
webui: http://[HOST]:[PORT:8888]/
