arch:
- aarch64
- amd64
- armv7
- i386
backup_exclude:
- '**/Plex Media Server/Cache/**'
- '**/Plex Media Server/Plug-in Support/Caches/**'
- '**/Plex Media Server/Logs/**'
- '**/Plex Media Server/Crash Reports/**'
- '**/Plex Media Server/Diagnostics/**'
codenotary: baris@ozdag.net
description: Recorded media, live TV, online news, and podcasts ready to stream.
hassio_api: true
image: ghcr.io/barisozdag/plex-apsw/{arch}
map:
- media:rw
- share:rw
- ssl
name: Plex Media Server
options:
  claim_code: ''
  webtools: false
ports:
  1900/udp: 1900
  3005/tcp: 3005
  32400/tcp: 32400
  32410/udp: 32410
  32412/udp: 32412
  32413/udp: 32413
  32414/udp: 32414
  32469/tcp: 32469
  33400/tcp: 33400
  33443/tcp: 33443
  8324/tcp: 8324
ports_description:
  1900/udp: Plex DLNA Server
  3005/tcp: Plex Home Theater via Plex Companion
  32400/tcp: Plex Media Server Interface
  32410/udp: GDM network discovery
  32412/udp: GDM network discovery
  32413/udp: GDM network discovery
  32414/udp: GDM network discovery
  32469/tcp: Plex DLNA Server
  33400/tcp: WebTools
  33443/tcp: WebTools
  8324/tcp: Plex for Roku via Plex Companion
schema:
  claim_code: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  webtools: bool
slug: plex-apsw
startup: services
url: https://github.com/barisozdag/addon-plex
version: 0.4.9
webui: http://[HOST]:[PORT:32400]/web
